# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - richkflaskapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Generate coverage report
      run: |
        pip install unittest
        pip install coverage
        coverage run -m unittest tests/*_.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests

    - uses: jorelali/setup-elm@v2
      with:
        elm-version: 0.19.1
    - run: |
           cd spa
           elm make src/Main.elm --output=../static/elm2.js

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.7'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'richkflaskapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d4b7ddad31d74066a9103653c6429dc4 }}